version: '3'
services:
  web:
    container_name: web
    build: ./docker/web
    depends_on:
      # - db
      - db_admin
      - redis
    volumes:
      # - ./web/php.ini:/usr/local/etc/php/php.ini
      # - ./sources/.:/var/www/html
      # - ./sources/proc/.:/var/www/html
      # - ./sources/laravel_pj/.:/var/www/html
      # - ./sources/admin/.:/var/www/html
      - ./sources/.:/var/www/html
      - ./logs:/var/log/apache2
      # - ./docker/web/httpd-vhosts.conf:/etc/apache2/sites-available/httpd-vhosts.conf
      - ./docker/web/apache_conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      # SSL設定
      # - ./docker/web/apache_conf/ssl.conf:/etc/apache2/sites-available/ssl.conf
      # - ./ssl/:/etc/ssl/keys
      # - ./ssl/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      # - ./ssl/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis
    container_name: redis

  # db:
  #   # image: postgres
  #   image: mysql:5.7
  #   container_name: mysql5.7
  #   # image: mysql:5.6
  #   # container_name: mysql5.6
  #   volumes:
  #   - mysql-db:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_DATABASE: lara
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: secret

  db_admin:
    # image: postgres
    image: mysql:5.7
    container_name: mysql5.7_admin
    # image: mysql:5.6
    # container_name: mysql5.6
    volumes:
    - mysql-db-admin:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

volumes:
  # mysql-db:
  mysql-db-admin:
