version: '3'
services:
  web:
    container_name: web
    build: ./docker/web
    depends_on:
      - db
      - redis
    volumes:
      # - ./web/php.ini:/usr/local/etc/php/php.ini
      # - ./sources/.:/var/www/html
      # - ./sources/proc/.:/var/www/html
      - ./sources/laravel_pj/.:/var/www/html
      # - ./sources/.:/var/www/html
    ports:
      - "80:80"
      # - "443:443"

  redis:
    image: redis
    container_name: redis

  db:
    # image: postgres
    image: mysql:5.6
    container_name: mysql5.6
    volumes:
    - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lara
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

volumes:
  mysql-db:
